# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eulerlauncher/grpcs/eulerlauncher_grpc/images.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'eulerlauncher/grpcs/eulerlauncher_grpc/images.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3eulerlauncher/grpcs/eulerlauncher_grpc/images.proto\x12\reulerlauncher\"7\n\x05Image\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"\x12\n\x10ListImageRequest\"9\n\x11ListImageResponse\x12$\n\x06images\x18\x01 \x03(\x0b\x32\x14.eulerlauncher.Image\"$\n\x14\x44ownloadImageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\".\n\x10LoadImageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"\"\n\x12\x44\x65leteImageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"0\n\x14GeneralImageResponse\x12\x0b\n\x03ret\x18\x01 \x01(\r\x12\x0b\n\x03msg\x18\x02 \x01(\t2\xf4\x02\n\x10ImageGrpcService\x12R\n\x0blist_images\x12\x1f.eulerlauncher.ListImageRequest\x1a .eulerlauncher.ListImageResponse\"\x00\x12\\\n\x0e\x64ownload_image\x12#.eulerlauncher.DownloadImageRequest\x1a#.eulerlauncher.GeneralImageResponse\"\x00\x12T\n\nload_image\x12\x1f.eulerlauncher.LoadImageRequest\x1a#.eulerlauncher.GeneralImageResponse\"\x00\x12X\n\x0c\x64\x65lete_image\x12!.eulerlauncher.DeleteImageRequest\x1a#.eulerlauncher.GeneralImageResponse\"\x00\x42\x03\x80\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eulerlauncher.grpcs.eulerlauncher_grpc.images_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\001'
  _globals['_IMAGE']._serialized_start=70
  _globals['_IMAGE']._serialized_end=125
  _globals['_LISTIMAGEREQUEST']._serialized_start=127
  _globals['_LISTIMAGEREQUEST']._serialized_end=145
  _globals['_LISTIMAGERESPONSE']._serialized_start=147
  _globals['_LISTIMAGERESPONSE']._serialized_end=204
  _globals['_DOWNLOADIMAGEREQUEST']._serialized_start=206
  _globals['_DOWNLOADIMAGEREQUEST']._serialized_end=242
  _globals['_LOADIMAGEREQUEST']._serialized_start=244
  _globals['_LOADIMAGEREQUEST']._serialized_end=290
  _globals['_DELETEIMAGEREQUEST']._serialized_start=292
  _globals['_DELETEIMAGEREQUEST']._serialized_end=326
  _globals['_GENERALIMAGERESPONSE']._serialized_start=328
  _globals['_GENERALIMAGERESPONSE']._serialized_end=376
  _globals['_IMAGEGRPCSERVICE']._serialized_start=379
  _globals['_IMAGEGRPCSERVICE']._serialized_end=751
# @@protoc_insertion_point(module_scope)
