# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from eulerlauncher.grpcs.eulerlauncher_grpc import instances_pb2 as eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in eulerlauncher/grpcs/eulerlauncher_grpc/instances_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InstanceGrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.list_instances = channel.unary_unary(
                '/eulerlauncher.InstanceGrpcService/list_instances',
                request_serializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ListInstancesRequest.SerializeToString,
                response_deserializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ListInstancesResponse.FromString,
                _registered_method=True)
        self.create_instance = channel.unary_unary(
                '/eulerlauncher.InstanceGrpcService/create_instance',
                request_serializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.CreateInstanceRequest.SerializeToString,
                response_deserializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.CreateInstanceResponse.FromString,
                _registered_method=True)
        self.delete_instance = channel.unary_unary(
                '/eulerlauncher.InstanceGrpcService/delete_instance',
                request_serializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.DeleteInstanceRequest.SerializeToString,
                response_deserializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.DeleteInstanceResponse.FromString,
                _registered_method=True)
        self.suspend_instance = channel.unary_unary(
                '/eulerlauncher.InstanceGrpcService/suspend_instance',
                request_serializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.SuspendInstanceRequest.SerializeToString,
                response_deserializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.SuspendInstanceResponse.FromString,
                _registered_method=True)
        self.resume_instance = channel.unary_unary(
                '/eulerlauncher.InstanceGrpcService/resume_instance',
                request_serializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ResumeInstanceRequest.SerializeToString,
                response_deserializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ResumeInstanceResponse.FromString,
                _registered_method=True)
        self.console_instance = channel.unary_unary(
                '/eulerlauncher.InstanceGrpcService/console_instance',
                request_serializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ConsoleInstanceRequest.SerializeToString,
                response_deserializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ConsoleInstanceResponse.FromString,
                _registered_method=True)


class InstanceGrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def list_instances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create_instance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_instance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def suspend_instance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def resume_instance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def console_instance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InstanceGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'list_instances': grpc.unary_unary_rpc_method_handler(
                    servicer.list_instances,
                    request_deserializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ListInstancesRequest.FromString,
                    response_serializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ListInstancesResponse.SerializeToString,
            ),
            'create_instance': grpc.unary_unary_rpc_method_handler(
                    servicer.create_instance,
                    request_deserializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.CreateInstanceRequest.FromString,
                    response_serializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.CreateInstanceResponse.SerializeToString,
            ),
            'delete_instance': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_instance,
                    request_deserializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.DeleteInstanceRequest.FromString,
                    response_serializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.DeleteInstanceResponse.SerializeToString,
            ),
            'suspend_instance': grpc.unary_unary_rpc_method_handler(
                    servicer.suspend_instance,
                    request_deserializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.SuspendInstanceRequest.FromString,
                    response_serializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.SuspendInstanceResponse.SerializeToString,
            ),
            'resume_instance': grpc.unary_unary_rpc_method_handler(
                    servicer.resume_instance,
                    request_deserializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ResumeInstanceRequest.FromString,
                    response_serializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ResumeInstanceResponse.SerializeToString,
            ),
            'console_instance': grpc.unary_unary_rpc_method_handler(
                    servicer.console_instance,
                    request_deserializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ConsoleInstanceRequest.FromString,
                    response_serializer=eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ConsoleInstanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eulerlauncher.InstanceGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eulerlauncher.InstanceGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InstanceGrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def list_instances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eulerlauncher.InstanceGrpcService/list_instances',
            eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ListInstancesRequest.SerializeToString,
            eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ListInstancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def create_instance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eulerlauncher.InstanceGrpcService/create_instance',
            eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.CreateInstanceRequest.SerializeToString,
            eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.CreateInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_instance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eulerlauncher.InstanceGrpcService/delete_instance',
            eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.DeleteInstanceRequest.SerializeToString,
            eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.DeleteInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def suspend_instance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eulerlauncher.InstanceGrpcService/suspend_instance',
            eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.SuspendInstanceRequest.SerializeToString,
            eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.SuspendInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def resume_instance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eulerlauncher.InstanceGrpcService/resume_instance',
            eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ResumeInstanceRequest.SerializeToString,
            eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ResumeInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def console_instance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eulerlauncher.InstanceGrpcService/console_instance',
            eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ConsoleInstanceRequest.SerializeToString,
            eulerlauncher_dot_grpcs_dot_eulerlauncher__grpc_dot_instances__pb2.ConsoleInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
