# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import instances_pb2 as instances__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in instances_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InstanceGrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.list_instances = channel.unary_unary(
                '/instances.InstanceGrpcService/list_instances',
                request_serializer=instances__pb2.ListInstancesRequest.SerializeToString,
                response_deserializer=instances__pb2.ListInstancesResponse.FromString,
                _registered_method=True)
        self.create_instance = channel.unary_unary(
                '/instances.InstanceGrpcService/create_instance',
                request_serializer=instances__pb2.CreateInstanceRequest.SerializeToString,
                response_deserializer=instances__pb2.CreateInstanceResponse.FromString,
                _registered_method=True)
        self.delete_instance = channel.unary_unary(
                '/instances.InstanceGrpcService/delete_instance',
                request_serializer=instances__pb2.DeleteInstanceRequest.SerializeToString,
                response_deserializer=instances__pb2.DeleteInstanceResponse.FromString,
                _registered_method=True)
        self.start_instance = channel.unary_unary(
                '/instances.InstanceGrpcService/start_instance',
                request_serializer=instances__pb2.StartInstanceRequest.SerializeToString,
                response_deserializer=instances__pb2.InstanceResponse.FromString,
                _registered_method=True)
        self.stop_instsance = channel.unary_unary(
                '/instances.InstanceGrpcService/stop_instsance',
                request_serializer=instances__pb2.StopInstanceRequest.SerializeToString,
                response_deserializer=instances__pb2.InstanceResponse.FromString,
                _registered_method=True)
        self.AttachDisk = channel.unary_unary(
                '/instances.InstanceGrpcService/AttachDisk',
                request_serializer=instances__pb2.AttachDiskRequest.SerializeToString,
                response_deserializer=instances__pb2.InstanceResponse.FromString,
                _registered_method=True)
        self.DetachDisk = channel.unary_unary(
                '/instances.InstanceGrpcService/DetachDisk',
                request_serializer=instances__pb2.DetachDiskRequest.SerializeToString,
                response_deserializer=instances__pb2.InstanceResponse.FromString,
                _registered_method=True)
        self.attach_disk = channel.unary_unary(
                '/instances.InstanceGrpcService/attach_disk',
                request_serializer=instances__pb2.AttachDiskRequest.SerializeToString,
                response_deserializer=instances__pb2.InstanceResponse.FromString,
                _registered_method=True)
        self.dettach_disk = channel.unary_unary(
                '/instances.InstanceGrpcService/dettach_disk',
                request_serializer=instances__pb2.DetachDiskRequest.SerializeToString,
                response_deserializer=instances__pb2.InstanceResponse.FromString,
                _registered_method=True)
        self.take_snapshot = channel.unary_unary(
                '/instances.InstanceGrpcService/take_snapshot',
                request_serializer=instances__pb2.TakeSnapshotRequest.SerializeToString,
                response_deserializer=instances__pb2.TakeSnapshotResponse.FromString,
                _registered_method=True)
        self.export_development_image = channel.unary_unary(
                '/instances.InstanceGrpcService/export_development_image',
                request_serializer=instances__pb2.ExportDevelopmentImageRequest.SerializeToString,
                response_deserializer=instances__pb2.ExportDevelopmentImageResponse.FromString,
                _registered_method=True)


class InstanceGrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def list_instances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create_instance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_instance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def start_instance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stop_instsance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttachDisk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetachDisk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def attach_disk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dettach_disk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def take_snapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def export_development_image(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InstanceGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'list_instances': grpc.unary_unary_rpc_method_handler(
                    servicer.list_instances,
                    request_deserializer=instances__pb2.ListInstancesRequest.FromString,
                    response_serializer=instances__pb2.ListInstancesResponse.SerializeToString,
            ),
            'create_instance': grpc.unary_unary_rpc_method_handler(
                    servicer.create_instance,
                    request_deserializer=instances__pb2.CreateInstanceRequest.FromString,
                    response_serializer=instances__pb2.CreateInstanceResponse.SerializeToString,
            ),
            'delete_instance': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_instance,
                    request_deserializer=instances__pb2.DeleteInstanceRequest.FromString,
                    response_serializer=instances__pb2.DeleteInstanceResponse.SerializeToString,
            ),
            'start_instance': grpc.unary_unary_rpc_method_handler(
                    servicer.start_instance,
                    request_deserializer=instances__pb2.StartInstanceRequest.FromString,
                    response_serializer=instances__pb2.InstanceResponse.SerializeToString,
            ),
            'stop_instsance': grpc.unary_unary_rpc_method_handler(
                    servicer.stop_instsance,
                    request_deserializer=instances__pb2.StopInstanceRequest.FromString,
                    response_serializer=instances__pb2.InstanceResponse.SerializeToString,
            ),
            'AttachDisk': grpc.unary_unary_rpc_method_handler(
                    servicer.AttachDisk,
                    request_deserializer=instances__pb2.AttachDiskRequest.FromString,
                    response_serializer=instances__pb2.InstanceResponse.SerializeToString,
            ),
            'DetachDisk': grpc.unary_unary_rpc_method_handler(
                    servicer.DetachDisk,
                    request_deserializer=instances__pb2.DetachDiskRequest.FromString,
                    response_serializer=instances__pb2.InstanceResponse.SerializeToString,
            ),
            'attach_disk': grpc.unary_unary_rpc_method_handler(
                    servicer.attach_disk,
                    request_deserializer=instances__pb2.AttachDiskRequest.FromString,
                    response_serializer=instances__pb2.InstanceResponse.SerializeToString,
            ),
            'dettach_disk': grpc.unary_unary_rpc_method_handler(
                    servicer.dettach_disk,
                    request_deserializer=instances__pb2.DetachDiskRequest.FromString,
                    response_serializer=instances__pb2.InstanceResponse.SerializeToString,
            ),
            'take_snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.take_snapshot,
                    request_deserializer=instances__pb2.TakeSnapshotRequest.FromString,
                    response_serializer=instances__pb2.TakeSnapshotResponse.SerializeToString,
            ),
            'export_development_image': grpc.unary_unary_rpc_method_handler(
                    servicer.export_development_image,
                    request_deserializer=instances__pb2.ExportDevelopmentImageRequest.FromString,
                    response_serializer=instances__pb2.ExportDevelopmentImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'instances.InstanceGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('instances.InstanceGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InstanceGrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def list_instances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instances.InstanceGrpcService/list_instances',
            instances__pb2.ListInstancesRequest.SerializeToString,
            instances__pb2.ListInstancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def create_instance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instances.InstanceGrpcService/create_instance',
            instances__pb2.CreateInstanceRequest.SerializeToString,
            instances__pb2.CreateInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_instance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instances.InstanceGrpcService/delete_instance',
            instances__pb2.DeleteInstanceRequest.SerializeToString,
            instances__pb2.DeleteInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def start_instance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instances.InstanceGrpcService/start_instance',
            instances__pb2.StartInstanceRequest.SerializeToString,
            instances__pb2.InstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def stop_instsance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instances.InstanceGrpcService/stop_instsance',
            instances__pb2.StopInstanceRequest.SerializeToString,
            instances__pb2.InstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AttachDisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instances.InstanceGrpcService/AttachDisk',
            instances__pb2.AttachDiskRequest.SerializeToString,
            instances__pb2.InstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetachDisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instances.InstanceGrpcService/DetachDisk',
            instances__pb2.DetachDiskRequest.SerializeToString,
            instances__pb2.InstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def attach_disk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instances.InstanceGrpcService/attach_disk',
            instances__pb2.AttachDiskRequest.SerializeToString,
            instances__pb2.InstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dettach_disk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instances.InstanceGrpcService/dettach_disk',
            instances__pb2.DetachDiskRequest.SerializeToString,
            instances__pb2.InstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def take_snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instances.InstanceGrpcService/take_snapshot',
            instances__pb2.TakeSnapshotRequest.SerializeToString,
            instances__pb2.TakeSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def export_development_image(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/instances.InstanceGrpcService/export_development_image',
            instances__pb2.ExportDevelopmentImageRequest.SerializeToString,
            instances__pb2.ExportDevelopmentImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
