[default]
log_dir = /Users/dengzhihang/Documents/workplace/log_dir
work_dir = /Users/dengzhihang/Documents/workplace/work_dir
wget_dir = /opt/homebrew/bin/wget
qemu_dir = /opt/homebrew/bin/qemu-system-aarch64
debug = True

[vm]
cpu_num = 1
memory = 1024