[default]
log_dir = /Users/dengzhihang/Documents/workplace/log_dir
work_dir = /Users/dengzhihang/Documents/workplace/work_dir
wget_bin = /opt/homebrew/bin/wget
qemu_bin = /opt/homebrew/bin/qemu-system-aarch64
virt-viewer_bin = /opt/homebrew/bin/virt-viewer
debug = True

[vm]
cpu_num = 1
memory = 1024