# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from omnivirt.grpcs.omnivirt_grpc import images_pb2 as images__pb2


class ImageGrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.list_images = channel.unary_unary(
                '/omnivirt.ImageGrpcService/list_images',
                request_serializer=images__pb2.ListImageRequest.SerializeToString,
                response_deserializer=images__pb2.ListImageResponse.FromString,
                )
        self.download_image = channel.unary_unary(
                '/omnivirt.ImageGrpcService/download_image',
                request_serializer=images__pb2.DownloadImageRequest.SerializeToString,
                response_deserializer=images__pb2.GeneralImageResponse.FromString,
                )
        self.load_image = channel.unary_unary(
                '/omnivirt.ImageGrpcService/load_image',
                request_serializer=images__pb2.LoadImageRequest.SerializeToString,
                response_deserializer=images__pb2.GeneralImageResponse.FromString,
                )
        self.delete_image = channel.unary_unary(
                '/omnivirt.ImageGrpcService/delete_image',
                request_serializer=images__pb2.DeleteImageRequest.SerializeToString,
                response_deserializer=images__pb2.GeneralImageResponse.FromString,
                )


class ImageGrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def list_images(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def download_image(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def load_image(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_image(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'list_images': grpc.unary_unary_rpc_method_handler(
                    servicer.list_images,
                    request_deserializer=images__pb2.ListImageRequest.FromString,
                    response_serializer=images__pb2.ListImageResponse.SerializeToString,
            ),
            'download_image': grpc.unary_unary_rpc_method_handler(
                    servicer.download_image,
                    request_deserializer=images__pb2.DownloadImageRequest.FromString,
                    response_serializer=images__pb2.GeneralImageResponse.SerializeToString,
            ),
            'load_image': grpc.unary_unary_rpc_method_handler(
                    servicer.load_image,
                    request_deserializer=images__pb2.LoadImageRequest.FromString,
                    response_serializer=images__pb2.GeneralImageResponse.SerializeToString,
            ),
            'delete_image': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_image,
                    request_deserializer=images__pb2.DeleteImageRequest.FromString,
                    response_serializer=images__pb2.GeneralImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omnivirt.ImageGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageGrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def list_images(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnivirt.ImageGrpcService/list_images',
            images__pb2.ListImageRequest.SerializeToString,
            images__pb2.ListImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def download_image(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnivirt.ImageGrpcService/download_image',
            images__pb2.DownloadImageRequest.SerializeToString,
            images__pb2.GeneralImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def load_image(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnivirt.ImageGrpcService/load_image',
            images__pb2.LoadImageRequest.SerializeToString,
            images__pb2.GeneralImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete_image(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnivirt.ImageGrpcService/delete_image',
            images__pb2.DeleteImageRequest.SerializeToString,
            images__pb2.GeneralImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
